# Generated by Django 4.2.13 on 2024-06-01 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("album", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicianModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=30)),
                ("lastName", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phone_no", models.CharField(max_length=12)),
                ("instrumentType", models.CharField(max_length=50)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="album.albummodel",
                    ),
                ),
            ],
        ),
    ]
